;; extends 

(("else" @conditional) (#set! conceal "e"))
(("elseif" @conditional) (#set! conceal "e"))
((function_call name: (identifier) @function.builtin (#eq? @function.builtin "require")) (#set! conceal "r"))
(("for" @repeat) (#set! conceal "F"))
(("function" @keyword.function) (#set! conceal "f"))
(("if" @conditional) (#set! conceal "?"))
(("in" @keyword) (#set! conceal "i"))
(("local" @keyword) (#set! conceal "l"))
(("do" @repeat) (#set! conceal "d"))
(("end" @keyword.function) (#set! conceal "E"))
(("and" @keyword.function) (#set! conceal "&"))
(("return" @keyword.function) (#set! conceal "R"))
(("then" @conditional) (#set! conceal "t"))
